# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"


  lane :cer do
     # Download certifications and provision profiles

     match(app_identifier: ["com.healmax.SnakeGame"], type: "development", readonly: true)
     match(app_identifier: ["com.healmax.SnakeGame"], type: "appstore", readonly: true)
  end


  lane :deliver_to_testflight do

    # Sync certificates
    cer

    # build your iOS app
    gym(
      scheme: "SnakeGame",
      export_method: "app-store"
    )

    # upload to Testflight
    testflight(skip_waiting_for_build_processing: true)

  end


  lane :release do
    build_app(workspace: "SnakeGame.xcworkspace", scheme: "SnakeGame")
    upload_to_app_store
  end
end
